NEW CMS 5 compatability
silverstripe/silverstripe-module pull request #41
Opened 2023-05-04 02:05 UTC by GuySartorelli

## Issue
- https://github.com/silverstripe/silverstripe-module/issues/40

2023-05-10 10:44 UTC, maxime-rainville requested changes
This looks great. I ran this locally to make sure I could create a module with it.

Made some suggestion, but I'm not overly wedged to any of them.

2023-05-10 10:44 UTC, maxime-rainville commented on CONTRIBUTING.md
> +- Please follow the Silverstripe [code contribution guidelines](https://docs.silverstripe.org/en/contributing/code/) and [Module Standard](https://docs.silverstripe.org/en/developer_guides/extending/
```suggestion
- Please follow the Silverstripe CMS [code contribution guidelines](https://docs.silverstripe.org/en/contributing/code/) and [Module Standard](https://docs.silverstripe.org/en/developer_guides/extending/modules/#module-standard)
```

2023-05-10 10:44 UTC, maxime-rainville commented on CONTRIBUTING.md
> +- When having discussions about this module in issues or pull request please adhere to the [Silverstripe Community Code of Conduct](https://docs.silverstripe.org/en/project_governance/code_of_conduct
```suggestion
- When having discussions about this module in issues or pull request please adhere to the [Silverstripe CMS Community Code of Conduct](https://docs.silverstripe.org/en/project_governance/code_of_conduct/)
```

2023-05-10 10:44 UTC, maxime-rainville commented on README.md
> +# Silverstripe supported module skeleton
```suggestion
# Silverstripe CMS supported module skeleton
```

2023-05-10 10:44 UTC, maxime-rainville commented on README.md
> +# Silverstripe supported module skeleton
```suggestion
# Silverstripe CMS supported module skeleton
```

2023-05-10 10:44 UTC, maxime-rainville commented on README.md
> +  - If you are relying on additional dependencies from `silverstripe/admin` instead of adding them as dependencies in your `package.json` file, you need to install third party dependencies in `silver
We need a better way of explaining this thing. But that will do for now.

2023-05-10 10:44 UTC, maxime-rainville commented on README.md
> +it is one of the most permissive and open licenses.
I'm not sure we "advocate" a specific license.

```suggestion
This module template defaults to using the "BSD-3-Clause" license. The BSD-3 license is one of the most
permissive open-source license and is used by most Silverstripe CMS module.
```

2023-05-10 10:44 UTC, maxime-rainville commented on README.md
> +you also update the license in your `composer.json` file if you do change the license for your project.
I think this is a bit more to the point.
```suggestion
To publish your module under a different license:
- update the [`license.md`](LICENSE.md) file
- update the `license' key in your [`composer.json`](composer.json).
```

2023-05-10 10:44 UTC, maxime-rainville commented on README.md
> +You can use [choosealicense.com](https://choosealicense.com) to help pick a suitable license for your project.
```suggestion
You can use [choosealicense.com](https://choosealicense.com) to help you pick a suitable license for your project.
```

2023-05-10 10:44 UTC, maxime-rainville commented on client/dist/js/bundle.js
Why do we even have distribution files on this thing?

2023-05-10 10:44 UTC, maxime-rainville commented on client/src/boot/README.md
> +See the [Silverstripe CMS javascript documentation](https://docs.silverstripe.org/en/developer_guides/customising_the_admin_interface/javascript_development/)
Good call!

2023-05-10 10:44 UTC, maxime-rainville commented on README.md
> +it is one of the most permissive and open licenses.
Just realised this was copied from somewhere else. If my suggesting wording is controversial, I'm happy to ditch it.

2023-05-10 21:10 UTC, GuySartorelli commented on README.md
> +# Silverstripe supported module skeleton
Isn't this the same as https://github.com/silverstripe/silverstripe-module/pull/41#discussion_r1189203791?

2023-05-10 21:13 UTC, GuySartorelli commented on client/dist/js/bundle.js
Because they were already there. 🤷‍♀️ Don't see that it matters either way. At worst it's just files that someone has to delete or override later, but that's this entire skeleton. At best it indicates what the exact output of building out the resources will be, which someone may find useful maybe?

At least it actually _does_ build out now, which it didn't do before 😅

2023-05-10 21:14 UTC, GuySartorelli commented on README.md
> +You can use [choosealicense.com](https://choosealicense.com) to help pick a suitable license for your project.
Done

2023-05-10 21:14 UTC, GuySartorelli commented on README.md
> +you also update the license in your `composer.json` file if you do change the license for your project.
Done

2023-05-10 21:14 UTC, GuySartorelli commented on README.md
> +it is one of the most permissive and open licenses.
Done

2023-05-10 21:14 UTC, GuySartorelli commented on README.md
> +# Silverstripe supported module skeleton
Done

2023-05-10 21:14 UTC, GuySartorelli commented on CONTRIBUTING.md
> +- When having discussions about this module in issues or pull request please adhere to the [Silverstripe Community Code of Conduct](https://docs.silverstripe.org/en/project_governance/code_of_conduct
Done

2023-05-10 21:14 UTC, GuySartorelli commented on CONTRIBUTING.md
> +- Please follow the Silverstripe [code contribution guidelines](https://docs.silverstripe.org/en/contributing/code/) and [Module Standard](https://docs.silverstripe.org/en/developer_guides/extending/
Done

2023-05-11 21:10 UTC, maxime-rainville approved these changes
LGTM

2023-05-11 21:10 UTC, merged